// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDep_3FBANQZegt28rtbE35IOivipttNOc',
    appId: '1:956885894538:android:c83c095c6dd9176d20f473',
    messagingSenderId: '956885894538',
    projectId: 'notification-388f1',
    storageBucket: 'notification-388f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbouUtEyWr8KJLO1VldcTQ95w6bZdPa08',
    appId: '1:956885894538:ios:55499f6f092f358e20f473',
    messagingSenderId: '956885894538',
    projectId: 'notification-388f1',
    storageBucket: 'notification-388f1.firebasestorage.app',
    iosBundleId: 'com.example.smartsystemforschools',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKle77RYchIZfeK7PrBJsUPqrBK4tCb1M',
    appId: '1:956885894538:web:856a737303000bc820f473',
    messagingSenderId: '956885894538',
    projectId: 'notification-388f1',
    authDomain: 'notification-388f1.firebaseapp.com',
    storageBucket: 'notification-388f1.firebasestorage.app',
    measurementId: 'G-EGG1XLB0R0',
  );
}
